engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
        - typescript
        - python
        - php
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "**.inc"
    - "**.js"
    - "**.ts"
    - "**.tsx"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
exclude_paths:
  - test/*
plugins:
  tslint:
    enabled: true
    config: tslint.json
